name: Java CI

on: [push]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3.6.0
      with:
        distribution: adopt
        java-version: 17
    - name: Build Jar
      run: chmod +x ./gradlew; ./gradlew deploy -Duse-k2
    - name: Upload built jar file
      uses: actions/upload-artifact@v3
      with:
        name: kotmindy
        path: ./lib.jar
